use_cloudfront: true
cloudfront_domain: d55udxcumsrf1.cloudfront.net
s3_bucket: paulmwatson
s3_permission: public_read
s3_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

javascripts:
  common:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/jquery.aw-showcase.min.js
    - public/javascripts/application.js

stylesheets:
  base2:
    - public/stylesheets/reset.css
    - public/stylesheets/showcase.css
    - public/stylesheets/showcase-style-5.css
    - public/stylesheets/fonts.css
    - public/stylesheets/base.css
    - public/stylesheets/buttons.css
    - public/stylesheets/home.css