javascripts:
  common3:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/application.js

stylesheets:
  base4:
    - public/stylesheets/reset.css
    - public/stylesheets/fonts.css
    - public/stylesheets/base.css
    - public/stylesheets/buttons.css
    - public/stylesheets/home.css
    - public/stylesheets/support.css
