apps:
  production: paulmwatson
  staging: paulmwatson-staging

stacks:
  all: bamboo-mri-1.9.2

config:
  all:
    BUNDLE_WITHOUT: "test:development"

collaborators:
  all:
    - "heroku@paulmwatson.com"

domains:
  production:
    - "paulmwatson.com"
    - "www.paulmwatson.com"

addons:
  all:
    - custom_domains:basic
    - logging:expanded
    - shared-database:5mb

  production:
    - exceptional:basic
    - newrelic:bronze
